### ISSUE TITLE
move orders enhancement - formations!

### ISSUE THREAD

**Issue by gammata** [vThaldren/Total-Annihilation-Developments#26]
See various Spring mods such as BAR for examples. See also zero k - https://www.youtube.com/watch?v=if8g0YIDJ7s

**Comment by gammata** [comment]
So this would be 2 functions:
1. Click M/Move and draw a line, units will line up along the line
2. Make clearer between whether units will hold their formation by holding Alt key, or just single click to try to move to a single point and bunch up (and then spread out again if they are aircraft)

**Comment by vThaldren** [comment]
has been implemented separately in dsound.dll - closing to indicate first progress
